"""scripts/validate_df3d_meshes.py — issue #42 sub-task 1.2.

Try loading every DF3D mesh through Mitsuba. Catch failures (invalid normals,
parse errors, OOM, etc.) before they kill a long Stage 1 cluster run.

Usage from repo root:

    python scripts/validate_df3d_meshes.py

Output:
    meshes/df3d/known_bad.txt  — one line per failing garment:
        <id>\t<error message>

Exit code 0 = ran to completion. Non-zero only on script-level errors (Mitsuba
import failure, df3d folder missing). Mesh-level failures are recorded in the
output file and reported as a final summary.
"""

from __future__ import annotations

import glob
import os
import sys
import time

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

try:
    import mitsuba as mi
    mi.set_variant("scalar_rgb")
except ImportError as e:
    print(f"FAIL: mitsuba not importable: {e}")
    sys.exit(1)

from cloth_pipeline.paths import DF3D_MESHES_DIR


def main() -> int:
    if not os.path.exists(DF3D_MESHES_DIR):
        print(f"FAIL: {DF3D_MESHES_DIR} does not exist")
        return 1

    # Match the recursive glob used by render_loop.py so we test the same set.
    mesh_files = sorted(
        glob.glob(os.path.join(DF3D_MESHES_DIR, "**", "*.obj"), recursive=True)
    )
    n_total = len(mesh_files)
    print(f"[validate] found {n_total} DF3D .obj files under {DF3D_MESHES_DIR}")
    if n_total == 0:
        print("FAIL: no .obj files found — symlink missing or empty?")
        return 1

    out_path = os.path.join(REPO_ROOT, "meshes", "df3d", "known_bad.txt")
    n_ok = 0
    n_bad = 0
    bad_lines: list[str] = []
    t0 = time.time()

    for i, mesh_path in enumerate(mesh_files, 1):
        rel = os.path.relpath(mesh_path, REPO_ROOT)
        # Garment id is the parent folder name (e.g. "1-1" for .../all/1-1/model_cleaned.obj)
        garment_id = os.path.basename(os.path.dirname(mesh_path))
        try:
            mi.load_dict({"type": "obj", "filename": mesh_path})
            n_ok += 1
        except Exception as e:
            n_bad += 1
            err = str(e).replace("\n", " ").replace("\t", " ")[:200]
            bad_lines.append(f"{garment_id}\t{err}")
            print(f"[FAIL] {rel} — {err}")

        if i % 100 == 0 or i == n_total:
            elapsed = time.time() - t0
            print(f"[progress] {i}/{n_total} ok={n_ok} bad={n_bad} elapsed={elapsed:.0f}s")

    # Write known_bad.txt (empty if all passed).
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(
            "# DF3D garments that fail Mitsuba load.\n"
            "# Format:  <garment-id>\\t<error>\n"
            f"# Generated by scripts/validate_df3d_meshes.py on {time.strftime('%Y-%m-%d %H:%M')}\n"
        )
        for line in bad_lines:
            f.write(line + "\n")

    elapsed = time.time() - t0
    print()
    print(f"=== Summary ===")
    print(f"  total tested:  {n_total}")
    print(f"  ok:            {n_ok}")
    print(f"  bad:           {n_bad}")
    print(f"  elapsed:       {elapsed:.0f}s")
    print(f"  output:        {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
